#!/bin/bash 

for i in 0 1 2 3 4 5 6 7 8 9;
do
find -type f -name "main.cpp" -exec sed -i "s/res[0-9]/res$i/g" {} \;
find -type f -name "main.cpp" -exec sed -i "s/\"red[0-9]/\"red$i/g" {} \;
find -type f -name "main.cpp" -exec sed -i "s/\"green[0-9]/\"green$i/g" {} \;
find -type f -name "main.cpp" -exec sed -i "s/\"blue[0-9]/\"blue$i/g" {} \;
c++ `Magick++-config --cxxflags --cppflags` -O2 -o main main.cpp \
 `Magick++-config --ldflags --libs` ;
./main;
done; 
