#!/bin/bash 

for i in 0 1 2 3 4 5 6 7 8 9;
do
find -type f -name "ip_opencv_canny.cpp" -exec sed -i "s/res[0-9]/res$i/g" {} \;
g++ -o ip_opencv_canny ip_opencv_canny.cpp `pkg-config opencv --cflags --libs`;
./ip_opencv_canny;
done
